name: NextJS Start Script Workflow

# When will the workflow be executed
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["NextJS Build Script Workflow"]  # Name of the test workflow
    types:
      - completed

# Operations
jobs:
  test-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          
      - name: Install dependencies
        run: npm ci # Installs dependencies locked in the package-lock.json file
      
      - name: Start Execution
        run: npm run start